FROM eclipse-temurin:11.0.28_6-jre-noble

ADD ./build/libs/openapi-mcp-server-*-all.jar /opt/app.jar

ENTRYPOINT ["java", "-Dlogback.statusListenerClass=ch.qos.logback.core.status.NopStatusListener", "-jar", "/opt/app.jar"]